name: novus
channels:
  - conda-forge
dependencies:
  - python=3.11
  - streamlit
  - fastapi
  - uvicorn
  - aiohttp
  - httpx
  - pandas
  - numpy
  - sqlalchemy
  - asyncpg
  - scikit-learn          
  - pydantic
  - python-dotenv
  - pandas
  - matplotlib
  - pip
  - pip:
      - pydantic-settings
      - tenacity            
      - llama-index
      - langchain
      - langchain_community
      - langchain_google_genai
      - chromadb
      - reportlab       
      - weasyprint         
      - google-generativeai      
